### PR TITLE
fix(commons): import isBot after rework of commons

### LINKED ISSUE #2063: tmi.js requires update
### Actual behavior
After rework forgot we import whole commons file, not functions, so we need update isBot to -> commons.isBot

### PR DESCRIPTION
**Pull request by Banonevar**
Fixes #2063

###### CHECKLIST

- [ ] tests are changed or added
- [ ] documentation is changed or added
- [ ] locales are changed or added
- [ ] db relationship (tools/database) are changed or added
- [ ] commit message follows [commit guidelines](https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines)

### CODE REVIEW

File: src/bot/tmi.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ class TMI extends Core {
       this.client[type].chat.on('WHISPER', async (message) => {
         message.tags.username = this.getUsernameFromRaw(message._raw)
 
-        if (!(await isBot(message.tags.username)) || !message.isSelf) {
+        if (!(commons.isBot(message.tags.username)) || !message.isSelf) {
```
Comment (sogehige) [inline src/bot/tmi.js]: You can change `!(commons.isBot(sender.username))` -> `!commons.isBot(sender.username)`

Comment (sogehige) [reply src/bot/tmi.js]: Same applies to other changes

**Comment by sogehige** [comment]
Please rebase, then it should work
